# Configurações do Banco de Dados (MySQL)
spring.datasource.url=jdbc:mysql://db:3306/wormless_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=wormless_admin
spring.datasource.password=wormless_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true